[package]
name = "Limonka"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.5.0"
glam = "0.15.2"
bvh = "0.5.0"
serde_json = "1.0"
